spring.application.name=spring_kotlin_final_demo
spring.profiles.active=local
spring.data.mongodb.auto-index-creation = true
server.error.include-message=always
server.error.include-binding-errors=always

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notes-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer